server:
  port: ${APPLICATION_PORT:5002}
  tomcat:
    max-swallow-size: -1
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5436/knuhub_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:knudevpass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: liquibase
    change-log: classpath:db/master.yaml
  jackson:
    time-zone: Europe/Kiev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID:-}
            client-secret: ${CLIENT_SECRET:-}

logging:
  level:
    org:
      springframework:
        web: debug
        transaction:
          support:
            TransactionSynchronizationUtils: info

application:
  base-url: ${BASE_URL:http://localhost:5002}
  minio:
    internal-url: ${MINIO_INTERNAL_URL:http://minio:9000}
    external-url: ${MINIO_EXTERNAL_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    use-proxy: ${MINIO_USE_PROXY:false}
  files:
    images:
      allowed-extensions:
        - jpg
        - jpeg
        - png
        - webp
      maximum-size-in-kilobytes: 2048
    pdfs:
      tasks:
        allowed-extensions:
          - pdf
        maximum-size-in-kilobytes: 5120
  jwt:
    signing-secret: ${JWT_SIGNING_SECRET:your-secure-secret}
    issuer: KNUdev
    expiration: 600000 #10 minutes
    refresh-token:
      expiration: 1440000 #24 hours

springdoc:
  swagger-ui:
    path: /api/documentation